apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-frontend
  template:
    metadata:
      labels:
        app: portfolio-frontend
    spec:
      containers:
        - name: portfolio-frontend
          image: portfolio-frontend:latest   # Always use local image
          imagePullPolicy: Never             # Never pull from Docker Hub
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portfolio-config
