version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:stable

jobs:
  build-and-push:
    executor: default
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Docker Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Build and Push Image
          command: |
            docker build -t aryankaushal7/portfolio-frontend:latest -f dockerstuff/Dockerfile .
            docker tag aryankaushal7/portfolio-frontend:latest aryankaushal7/portfolio-frontend:$CIRCLE_SHA1
            docker push aryankaushal7/portfolio-frontend:latest
            docker push aryankaushal7/portfolio-frontend:$CIRCLE_SHA1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push
