version: 2.1

executors:
  default:
    docker:
      - image: cimg/python:3.11  

jobs:
  deploy:
    executor: default
    steps:
      - checkout

      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update && sudo apt-get install -y awscli

      - run:
          name: Configure AWS Credentials
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region ap-south-1

      - run:
          name: Sync Files to S3
          command: |
            aws s3 sync ./ s3://aryan-portfolio-site-bucket --delete --exact-timestamps

      - run:
          name: Invalidate CloudFront Cache
          command: |
            aws cloudfront create-invalidation \
              --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
              --paths "/*"

      - run:
          name: Notify Deployment Success
          command: echo "CircleCI Deployment completed successfully."

workflows:
  deploy_workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
